jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline workflow

# TEST deployment to Heroku
  - name: heroku-deploy-test-sample
    type: runSh
    steps:
      - IN: int-heroku
      - IN: params-sample-test
      - IN: repo-sample
      - TASK:
        - script: . /build/IN/repo-sample/gitRepo/provInfra.sh repo-sample params-sample-test int-heroku
        - script: git remote add test git@heroku.com:sample-node-ayeaye-test.git
        - script: git push test master

# TEST deployment to Heroku
  - name: heroku-deploy-prod-sample
    type: runSh
    steps:
      - IN: int-heroku
      - IN: params-sample-prod
      - IN: repo-sample
      - TASK:
        - script: . /build/IN/repo-sample/gitRepo/provInfra.sh repo-sample params-sample-prod int-heroku
        - script: git remote add test git@heroku.com:sample-node-ayeaye-test.git
        - script: git push test master
